Adding geopackage layers to the current project
qgis/QGIS-Hub-Plugin pull request #47
Opened 2023-06-25 10:55 UTC by ronitjadhav

Added option to add the geopackage layers to the current project.

2023-06-26 04:06 UTC, ismailsunni requested changes

2023-06-29 04:33 UTC, ronitjadhav commented on qgis_hub_plugin/gui/resource_browser.py
> +        if file_path.endswith(".zip"):
@ismailsunni 
I tried to implement the suggested, but it fails to open the zip when I try to use ogr.Open(zipbase)

2023-07-03 07:59 UTC, ismailsunni commented on qgis_hub_plugin/gui/resource_browser.py
> +            self.tr("ZIP Files (*.zip)"),
it might be a `gpkg` also

2023-07-03 07:59 UTC, ismailsunni commented on qgis_hub_plugin/gui/resource_browser.py
> +        extract_location = Path(os.path.dirname(file_path))
The `extract_location` might be not what we expect.
For example:
Resource: QGIS Dashboard
Zip file name: `CasteloBrancoDashboardAnchored_X3UlC1k.zip`
gpkg file name: `CasteloBrancoDashboardAnchored.gpkg`

perhaps try to extract it to a directory, then scan the directory.

2023-07-05 15:08 UTC, merged